resolver: lts-9.21

packages:
- .

extra-deps: [
  hsqml-0.3.5.0
]

flags: {}

extra-package-dbs: [
]

# Dodatkowa konfiguracja potrzebna na system Windows:
#  - dostepna tylko i386 ze wzgledu na udostepnione biblioteki Qt
#  - potrzeba wyspecyfikowac sciezke do biblioteki Qt
# arch: i386
# extra-include-dirs:
#  - C:\Qt\
# extra-include-dirs:
# - C:\Qt\5.9.2\mingw53_32\include
# extra-lib-dirs:
# - C:\Qt\5.9.2\mingw53_32\lib
# - C:\Qt\5.9.2\mingw53_32\bin
